modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/noobanidus/grindr/issues" #optional
license="https://github.com/noobanidus/grinder/blob/1.16/LICENSE"
[[mods]]
modId="grinder" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Grinder" #mandatory
displayURL="https://minecraft.curseforge.com/projects/grinder" #optional
authors="Noobanidus"
escription='''
Modular grindstone!
'''
[[dependencies.Grinder]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.Grinder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
